"""deleted mistakes

Revision ID: 0b487787c565
Revises: e65e2e3ae8fd
Create Date: 2025-03-02 14:42:22.350493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b487787c565'
down_revision: Union[str, None] = 'e65e2e3ae8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        DELETE FROM seat_bookings
        WHERE booking_id IN (
            '7b0a7dd1-8385-476b-ba7a-48f6f810189c',
            '11abd110-1ef2-4b37-bf43-1f8a2ae09b99'
        )
        """
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
