"""delete all coworkings

Revision ID: 0e47abfac657
Revises: 3dfd7d812d93
Create Date: 2025-03-03 23:42:43.351913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e47abfac657'
down_revision: Union[str, None] = '3dfd7d812d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('seats_coworking_id_fkey', 'seats', type_='foreignkey')
    op.create_foreign_key(None, 'seats', 'coworkings', ['coworking_id'], ['coworking_id'], ondelete='CASCADE')
    op.drop_constraint('tables_coworking_id_fkey', 'tables', type_='foreignkey')
    op.create_foreign_key(None, 'tables', 'coworkings', ['coworking_id'], ['coworking_id'], ondelete='CASCADE')
    op.execute('DELETE FROM coworkings')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.alter_column('seats', 'seat_access_level',
               existing_type=postgresql.ENUM('GUEST', 'STANDARD', 'PRO', name='accesslevel'),
               nullable=True)
    op.alter_column('seat_bookings', 'seat_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
