"""changing seat_id from uuid to str

Revision ID: 1a7f5affb3be
Revises: a04bf0e27681
Create Date: 2025-03-04 02:40:37.519038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a7f5affb3be'
down_revision: Union[str, None] = 'a04bf0e27681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM seat_bookings")
    op.execute("DELETE FROM bookings")
    op.execute("DELETE FROM seats")

    op.alter_column(
        'seats',  # Название таблицы
        'seat_id',  # Название столбца
        type_=sa.Integer(),  # Новый тип данных
        existing_type=sa.String(length=50),  # Старый тип данных
        postgresql_using='seat_id::integer',  # Преобразование данных для PostgreSQL
        autoencreament=True
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ...