"""added passport_data variables

Revision ID: 3c8e35326f76
Revises: 6dc8a6b3e55b
Create Date: 2025-03-03 21:10:57.435281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c8e35326f76'
down_revision: Union[str, None] = '6dc8a6b3e55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passport_series', sa.String(), nullable=True))
    op.add_column('users', sa.Column('passport_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('passport_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passport_name')
    op.drop_column('users', 'passport_number')
    op.drop_column('users', 'passport_series')
    # ### end Alembic commands ###
