"""Add tz offset for coworkings

Revision ID: 63006692c655
Revises: e2cc80d78227
Create Date: 2025-03-02 11:04:29.645324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63006692c655'
down_revision: Union[str, None] = 'e2cc80d78227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('coworking_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.client_id'], ),
    sa.ForeignKeyConstraint(['coworking_id'], ['coworkings.coworking_id'], ),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.add_column('coworkings', sa.Column('tz_offset', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coworkings', 'tz_offset')
    op.drop_table('admins')
    # ### end Alembic commands ###
