"""Add seats price

Revision ID: 6dc8a6b3e55b
Revises: 491d2ee93e3c
Create Date: 2025-03-03 10:47:40.345004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dc8a6b3e55b'
down_revision: Union[str, None] = '491d2ee93e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('price', sa.Integer(), nullable=False, server_default='100'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seats', 'price')
    # ### end Alembic commands ###
