"""changed id for seats

Revision ID: 70db0a9f53bd
Revises: 7f848b9e3b51
Create Date: 2025-03-02 00:08:15.220428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '70db0a9f53bd'
down_revision: Union[str, None] = '7f848b9e3b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(text('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seat_bookings', 'seat_id')

    # Step 1 - Add column as nullable with default
    op.add_column('seats', sa.Column('seat_uuid', sa.UUID(), nullable=True))

    # Step 2 - Populate existing rows with some UUID
    seats = table('seats', column('seat_uuid', sa.UUID()))

    op.execute(
        seats.update().values(seat_uuid=sa.func.uuid_generate_v4())
    )

    # Step 3 - Alter column to NOT NULL
    op.alter_column('seats', 'seat_uuid', nullable=False)

    # Step 4 - Create primary key constraint
    op.create_primary_key(None, 'seats', ['seat_uuid'])

    op.create_foreign_key(None, 'seat_bookings', 'seats', ['seat_uuid'], ['seat_uuid'])
    op.alter_column('seats', 'seat_id',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    autoincrement=True)
    op.create_unique_constraint(None, 'seats', ['seat_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(text('DROP EXTENSION IF EXISTS "uuid-ossp";'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seats', type_='unique')
    op.alter_column('seats', 'seat_id',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    autoincrement=True)
    op.drop_column('seats', 'seat_uuid')
    op.add_column('seat_bookings', sa.Column('seat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'seat_bookings', type_='foreignkey')
    # ### end Alembic commands ###
