"""Update db model

Revision ID: 7388e59e0980
Revises:
Create Date: 2025-03-01 00:46:54.466758

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7388e59e0980"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seats",
        sa.Column("seat_id", sa.Uuid(), nullable=False),
        sa.Column("coworking_id", sa.String(), nullable=False),
        sa.Column(
            "seat_type",
            sa.Enum("AUDIENCE", "OPENSPACE", name="seattype"),
            nullable=False,
        ),
        sa.Column(
            "seat_access_level",
            sa.Enum("GUEST", "STUDENT", "ADMIN", name="seataccesslevel"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("seat_id"),
    )
    op.create_table(
        "users",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column(
            "access_level",
            sa.Enum("GUEST", "STUDENT", "ADMIN", name="user_status_enum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_table(
        "bookings",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("coworking_id", sa.String(), nullable=False),
        sa.Column("seat_id", sa.Uuid(), nullable=False),
        sa.Column("start_date", sa.String(), nullable=False),
        sa.Column("end_date", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["seat_id"],
            ["seats.seat_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.client_id"],
        ),
        sa.PrimaryKeyConstraint("booking_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bookings")
    op.drop_table("users")
    op.drop_table("seats")
    # ### end Alembic commands ###
