"""Add tables

Revision ID: 78c949fdf1e8
Revises: 987f66ee49b5
Create Date: 2025-03-03 21:41:08.892280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78c949fdf1e8'
down_revision: Union[str, None] = '987f66ee49b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tables',
        sa.Column('table_id', sa.UUID(), nullable=False),
        sa.Column('pos_x', sa.Float(), nullable=False),
        sa.Column('pos_y', sa.Float(), nullable=False),
        sa.Column('width', sa.Float(), nullable=False),
        sa.Column('height', sa.Float(), nullable=False),
        sa.Column('rx', sa.Float(), nullable=False),
        sa.Column('rotation', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('table_id')
    )

    op.add_column('seats', sa.Column('seat_type', sa.Enum('AUDIENCE', 'OPENSPACE', name='seattype'), nullable=False))
    op.add_column('seats', sa.Column('width', sa.Float(), nullable=False))
    op.add_column('seats', sa.Column('height', sa.Float(), nullable=False))
    op.add_column('seats', sa.Column('rx', sa.Float(), nullable=False))
    op.add_column('seats', sa.Column('rotation', sa.Float(), nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seats', 'rotation')
    op.drop_column('seats', 'rx')
    op.drop_column('seats', 'height')
    op.drop_column('seats', 'width')
    op.drop_column('seats', 'seat_type')
    op.alter_column('seat_bookings', 'user_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.alter_column('seat_bookings', 'seat_id',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_table('tables')
    # ### end Alembic commands ###
