"""kall

Revision ID: 88422c34f0f8
Revises: 0b487787c565
Create Date: 2025-03-02 18:32:14.501463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88422c34f0f8'
down_revision: Union[str, None] = '0b487787c565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat_bookings', sa.Column('seat_id', sa.String(), nullable=True))
    op.execute("DELETE FROM seat_bookings")

    # Удаление всех данных из таблицы booking
    op.execute("DELETE FROM bookings")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seat_bookings', 'seat_id')
    # ### end Alembic commands ###
