"""Fix seat id

Revision ID: 9b971ade50d5
Revises: 1a7f5affb3be
Create Date: 2025-03-04 03:40:26.848384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b971ade50d5'
down_revision: Union[str, None] = '1a7f5affb3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'seats', 'seat_id',
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'seats', 'seat_id',
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False
    )
    # ### end Alembic commands ###
