"""Add auth sessions tables

Revision ID: a7802ff39415
Revises: 7388e59e0980
Create Date: 2025-03-01 09:54:39.593299

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a7802ff39415"
down_revision: Union[str, None] = "7388e59e0980"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("token_uid", sa.String(), nullable=False),
        sa.Column("expire_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", "client_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auth_sessions")
    # ### end Alembic commands ###
