"""add static data for tests (students and admins)

Revision ID: bcadfc3fc076
Revises: b242d62063d7
Create Date: 2025-03-03 22:32:24.605033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision: str = 'bcadfc3fc076'
down_revision: Union[str, None] = 'b242d62063d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



users_data = [
    {
        "client_id": uuid.uuid4(),
        "username": "student",
        "email": "student@example.com",
        "access_level": "STUDENT",
        "verification_level": "PRO",
        "password": "$2b$12$TzZWyUlHGoYsqdTPaY..o./Sfeo7J9aqlkZfl.SCOaQqO96bT1kHC", # Adminnn15)!
    },
    {
        "client_id": uuid.uuid4(),
        "username": "admin",
        "email": "admin@example.com",
        "verification_level": "PRO",
        "access_level": "ADMIN",
        "password": "$2b$12$TzZWyUlHGoYsqdTPaY..o./Sfeo7J9aqlkZfl.SCOaQqO96bT1kHC", # Adminnn15)!
    },
    {
        "client_id": uuid.uuid4(),
        "username": "guest",
        "email": "guest@example.com",
        "verification_level": "GUEST",
        "access_level": "GUEST",
        "password": "$2b$12$TzZWyUlHGoYsqdTPaY..o./Sfeo7J9aqlkZfl.SCOaQqO96bT1kHC", # Adminnn15)!
    },
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        sa.table(
            "users",
            sa.column("client_id", sa.UUID),
            sa.column("username", sa.String),
            sa.column("email", sa.String),
            sa.column("access_level", sa.String),
            sa.column("verification_level", sa.String),
            sa.column("password", sa.String),
        ),
        users_data
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###
