version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydatabase
    ports:
      - "8032:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    
  backend:
    build: .
    container_name: backend
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network: